### ISSUE TITLE
DB Snapshot returns Error404

### ISSUE THREAD

**Issue by FarzanAkhtar1** [AlgoNode/light-indexer#1]
Hi

Within bin/catchup the RESTORE DATABASE function references https://snap.nodely.io/conduit-main/hourly/

This URL returns an error 404, causing the download to fail and will not repopulate the database.

**Comment by urtho** [comment]
The 404 error is normal as browsing is not possible on Cloudflare public R2 bucket.

The reason for light-indexer DB restore failure is actually this :
ERROR: backup from version 23.1 is older than the minimum restorable version 23.2

The snapshot is being done using older CDB version and the light-indexer is using "latest" CDB image which is now newer then the snapshot.

Let me fix this ...

**Comment by urtho** [comment]
New snapshot compatible with latest CockroachDB will be available in 2 hrs. 

We'll be migrating to a new (our own) store for snapshots next week as Cloufrade R2 is not stable.

**Comment by urtho** [comment]
OK, light indexer init / catchup should be working with latest CockroachDB.
