### ISSUE TITLE
Install Issue with Docker

### ISSUE THREAD

**Issue by bluesuedesw** [AlgoNode/light-indexer#2]
Hello,

Running on CentOS 7

Have docker, docker-compose and jq installed.

Running as root, and failing to install. Getting this error:

# ./bin/init
initializing one-bash-indexer
1/4 initializing configs
2/4 pulling images
unknown shorthand flag: 'f' in -f
See 'docker --help'.

Would love to get this up and running, any thoughts on workarounds?

**Comment by aleve99** [comment]
I was getting the same error as you. Resolved by editing docker compose in docker-compose but I had some certificate errors. Removing all previous docker installation and reinstalling following the official guide resolved the issues.

**Comment by urtho** [comment]
Install script assumes Docker v2 and docker compose plugin instead of old docker-compose.
As @aleve99 said - remove old docker v1 and install v2
